_format_version: "2.1"
_transform: true

services:
  - name: grand-oak
    url: http://host.docker.internal:7001/doctors
    routes:
      - name: grand-oak-hospital-schedule
        paths:
          - /grand-oak
        strip_path: true
  - name: pine-valley
    url: http://host.docker.internal:7002/appointments
    routes:
      - name: pine-valley-hospital-schedule
        paths:
          - /pine-valley
        strip_path: true
  - name: spruce-city
    url: http://host.docker.internal:7003/schedules
    routes:
      - name: spruce-city-hospital-schedule
        paths:
          - /spruce-city
        strip_path: true
  - name: hospital-schedule
    url: http://localhost # Dummy URL; aggregation handled by plugin
    routes:
      - name: hospital-schedule-route
        paths:
          - /hospital/schedules
        strip_path: true
    plugins:
      - name: aggregator
        config:
          grand_oak_service_url: "http://host.docker.internal:7001/doctors"
          pine_valley_service_url: "http://host.docker.internal:7002/appointments"
          spruce_city_service_url: "http://host.docker.internal:7003/schedules"
